{
  "openapi": "3.0.1",
  "info": {
    "title": "Users API",
    "version": "v1",
    "description": "Manage your users in Credentials.  Operations require the 'users:read', 'users:write', or 'users:delete' scopes.",
    "termsOfService": "https://support.hcss.com.",
    "contact": {
      "name": "Heavy Construction Systems Specialists, Inc. (HCSS)",
      "url": "https://support.hcss.com/",
      "email": "support@hcss.com"
    },
    "license": {
      "name": "EULA",
      "url": "https://support.hcss.com."
    }
  },
  "servers": [
    {
      "url": "https://api.hcssapps.com/users"
    }
  ],
  "security": [
    {
      "bearer": [
        "users:read",
        "users:write",
        "users:delete"
      ]
    }
  ],
  "paths": {
    "/api/v1/BusinessUnits": {
      "get": {
        "tags": [
          "BusinessUnits"
        ],
        "summary": "Returns all business units in a company",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token"
      }
    },
    "/api/v1/Jobs/GetJobsByBusinessUnit": {
      "get": {
        "tags": [
          "Jobs"
        ],
        "summary": "Returns all jobs in a business unit",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token"
      }
    },
    "/api/v1/Roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Returns all roles in a company",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token"
      }
    },
    "/api/v1/SubscriptionGroups": {
      "get": {
        "tags": [
          "SubscriptionGroups"
        ],
        "summary": "Returns all subscription groups in a company",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token"
      }
    },
    "/api/v1/Users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns all users in a company with paging",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token",
        "operationId": "Get"
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Creates a new user",
        "description": "<ul>\r\n  <li>Email is required when ContactMethod is 'Email'</li>\r\n  <li>PhoneNumber is required when ContactMethod is 'PhoneNumber'</li>\r\n  <li>BusinessUnitAccess.Values should be a list of Business Unit Ids when BusinessUnitAccess.Type is 'SelectedBusinessUnits'</li>\r\n  <li>BusinessUnitAccess.Values should be null when BusinessUnitAccess.Type is 'AllBusinessUnits'</li>\r\n  <li>JobAccess.Values should be null when JobAccess.Type is 'AllJobs'</li>\r\n</ul>\r\n    [...]",
        "operationId": "CreateUser"
      }
    },
    "/api/v1/Users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns user by id",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token",
        "operationId": "GetById"
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Updates a user",
        "description": "Only properties that are not null will be updated\r\n<ul><li>Email is required when ContactMethod is 'Email'</li><li>PhoneNumber is required when ContactMethod is 'PhoneNumber'</li><li>BusinessUnitAccess.Values should be a list of Business Unit Ids when BusinessUnitAccess.Type is 'SelectedBusinessUnits'</li><li>BusinessUnitAccess.Values should be null when BusinessUnitAccess.Type is 'AllBusinessUnits'</li><li>JobAccess.Values should be null when JobAccess.Type is 'AllJobs[...]",
        "operationId": "UpdateUser"
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Deletes a user with the given id",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token",
        "operationId": "DeleteUser"
      }
    },
    "/api/v1/Users/userName/{userName}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns user by username",
        "description": "For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token",
        "operationId": "GetByUsername"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearer": {
        "type": "oauth2",
        "description": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.hcssapps.com/identity/connect/token",
            "scopes": {
              "users:read": "users:read",
              "users:write": "users:write",
              "users:delete": "users:delete"
            }
          },
          "authorizationCode": {
            "tokenUrl": "https://api.hcssapps.com/identity/connect/token",
            "authorizationUrl": "https://api.hcssapps.com/identity/connect/authorize",
            "scopes": {
              "users:read": "users:read",
              "users:write": "users:write",
              "users:delete": "users:delete"
            }
          }
        }
      }
    }
  }
}