openapi: 3.0.1
info:
  title: HeavyJob API
  description: Get time cards, materials, budgets, and more. Operations require the 'heavyjob:read', 'heavyjob:write', 'timecards:read', or 'timecards:write' scope. For help with authorization, please visit https://developer.hcssapps.com/getting-started/request-token.
  version: v1
  termsOfService: https://support.hcss.com.
  contact:
    name: Heavy Construction Systems Specialists, Inc. (HCSS)
    url: https://support.hcss.com/
    email: support@hcss.com
  license:
    name: EULA
    url: https://support.hcss.com.
servers:
  - url: https://api.hcssapps.com/heavyjob
security:
  - bearer:
      - heavyjob:read
      - heavyjob:write
      - timecards:read
      - timecards:write
      - heavyjob:users:read
      - heavyjob:users:write
paths:
  /api/v1/accessGroup:
    get:
      tags:
        - AccessGroup
      summary: Returns access groups
      description: This call will return a list of access groups.
      operationId: AccessGroupController_GetAllRoles
      security:
        - bearer:
            - heavyjob:users:read
  /api/v1/accountingValues/search:
    post:
      tags:
        - Accounting
      summary: Returns a list of accounting values that satisfy the filter criteria.
      operationId: AccountingController_GetAccountingValuesAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/rateSetGroupAccountingValues/search:
    post:
      tags:
        - Accounting
      summary: Returns a list of rate set group accounting values that satisfy the filter criteria.
      operationId: AccountingController_GetRateSetGroupAccountingValuesAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobs/{jobId}/advancedBudgets/material:
    get:
      tags:
        - AdvancedBudget
      summary: Returns material advanced budgets
      description: "This call will return a list of material advanced budgets (i.e., the cartesian product of material cost types and cost codes) \r\nfor the specified job, purchase order, discontinued status or deleted status."
      operationId: AdvancedBudgetController_GetMaterialsAdvancedBudget
      security:
        - bearer:
            - heavyjob:read
  /api/v1/advancedBudgets/material:
    post:
      tags:
        - AdvancedBudget
      summary: Creates material advanced budget
      description: Creates a new material advanced budget with the information provided.
      operationId: AdvancedBudgetController_CreateMaterialAdvancedBudget
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobs/{jobId}/advancedBudgets/subcontract:
    get:
      tags:
        - AdvancedBudget
      summary: Returns subcontract work item advanced budgets
      description: "This call will return a list of subcontract item advanced budgets (i.e., the cartesian product of subcontract cost types and cost codes)\r\nfor the specified job."
      operationId: AdvancedBudgetController_GetSubcontractsAdvancedBudget
      security:
        - bearer:
            - heavyjob:read
  /api/v1/advancedBudgets/subcontract:
    post:
      tags:
        - AdvancedBudget
      summary: Creates subcontract advanced budget
      description: This call creates a new subcontract advanced budget with the information provided.
      operationId: AdvancedBudgetController_CreateSubcontractAdvancedBudget
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobs/{jobId}/advancedBudgets/custom:
    get:
      tags:
        - AdvancedBudget
      summary: Returns a list of user-defined custom cost-type items advanced budget (i.e., the cartesian product of custom cost types and cost codes).
      operationId: AdvancedBudgetController_GetCustomCostTypesAdvancedBudget
      security:
        - bearer:
            - heavyjob:read
  /api/v1/advancedBudgets/custom:
    post:
      tags:
        - AdvancedBudget
      summary: Creates a new custom-cost-type item advanced budget.
      operationId: AdvancedBudgetController_CreateCustomCostTypeItemAdvancedBudget
      security:
        - bearer:
            - heavyjob:write
  /api/v1/attachment:
    post:
      tags:
        - Attachment
      summary: Saves an attachment
      description: Used in conjunction with the <a href="https://developer.hcssapps.com/products/attachments/spec/tag/Files/#tag/Files/operation/Post" target="_blank">Attachments API</a> to associate an attachment to a foreman for a given date and job.
      operationId: AttachmentController_SaveAttachment
      security:
        - bearer:
            - heavyjob:write
  /api/v1/bulkCreateJobsRequest/search:
    post:
      tags:
        - BulkCreateJobsRequest
      summary: Returns bulk job creation requests
      description: "<span style='color: white; background-color: red; font-weight: bold; padding: 5px;'>VOLATILE</span>\n\t\t<span>The query parameters and responses are likely to change. Do not use this operation for mission-critical applications yet.</span>\n\t\t<br /><br />This call will return a list bulk job creation requests for the specified business unit id, batch id(s) or created between a date range."
      operationId: BulkCreateJobsRequestController_GetBulkCreateJobsRequestsAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/singleCreateJobsRequest/search:
    post:
      tags:
        - BulkCreateJobsRequest
      summary: Returns single job creation requests.
      description: "<span style='color: white; background-color: red; font-weight: bold; padding: 5px;'>VOLATILE</span>\n\t\t<span>The query parameters and responses are likely to change. Do not use this operation for mission-critical applications yet.</span>\n\t\t<br /><br />This endpoint will return information about individual jobs that were part of a bulk create request."
      operationId: BulkCreateJobsRequestController_GetSingleCreateJobsRequestAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/businessUnits:
    get:
      tags:
        - BusinessUnit
      summary: Returns business units
      description: This call returns a list of business units.
      operationId: BusinessUnitController_GetBusinessUnits
      security:
        - bearer:
            - heavyjob:read
  /api/v1/businessUnits/{id}/preferences:
    get:
      tags:
        - BusinessUnitPreference
      summary: Gets the list of preferences for the business unit.
      operationId: BusinessUnitPreferenceController_GetBusinessUnitPreferencesAsync
      security:
        - bearer:
            - heavyjob:read
    put:
      tags:
        - BusinessUnitPreference
      summary: Gets the list of preferences for the business unit.
      operationId: BusinessUnitPreferenceController_UpdateBusinessUnitPreferencesAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/changeOrder:
    get:
      tags:
        - ChangeOrder
      summary: Finds a change order by id.
      operationId: ChangeOrderController_GetChangeOrderAsync
      security:
        - bearer:
            - heavyjob:read
    delete:
      tags:
        - ChangeOrder
      summary: Deletes a change order by id.
      operationId: ChangeOrderController_DeleteChangeOrderAsync
      security:
        - bearer:
            - heavyjob:write
    post:
      tags:
        - ChangeOrder
      summary: Creates a change order.
      operationId: ChangeOrderController_CreateChangeOrderAsync
      security:
        - bearer:
            - heavyjob:write
    patch:
      tags:
        - ChangeOrder
      summary: Updates a change order.
      operationId: ChangeOrderController_UpdateChangeOrderAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/changeOrdersByJob:
    get:
      tags:
        - ChangeOrder
      summary: Finds all change orders by job id.
      operationId: ChangeOrderController_GetChangeOrdersByJobAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/changeOrdersByBU:
    get:
      tags:
        - ChangeOrder
      summary: Finds all change orders by business unit id.
      operationId: ChangeOrderController_GetChangeOrdersByBUAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/changeOrderChangesByBU:
    get:
      tags:
        - ChangeOrder
      summary: Finds all change orders by business unit id that have been updated since a given timestamp.
      operationId: ChangeOrderController_GetMobileChangeOrdersByBUAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/changeOrderIncrementor:
    get:
      tags:
        - ChangeOrder
      summary: Finds the change order incrementor data by business unit id.
      operationId: ChangeOrderController_GetChangeOrdersIncrementorAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobs/{jobId}/costs:
    get:
      tags:
        - Cost
      summary: Returns job costs
      description: This call returns job costs for the specified job, effective date or start date.
      operationId: CostController_GetJobCosts
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobCosts:
    get:
      tags:
        - Cost
      summary: Returns job costs associated with a cost code
      description: This call returns a paginated list of job costs associated with a cost code for a specified cost code, effective date or start date.
      operationId: CostController_GetJobCostByCostCode
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobCosts/advancedRequest:
    post:
      tags:
        - Cost
      summary: Returns costs and hours spent per cost code
      description: This call returns a paginated list of costs and hours spent per cost code for the specified business unit, cost codes, jobs, foremen, or date range.
      operationId: CostController_QueryJobCosts
      security:
        - bearer:
            - heavyjob:read
  /api/v2/jobCosts/advancedRequest:
    post:
      tags:
        - Cost
      summary: Returns job costs
      description: This call returns a paginated list of job costs.
      operationId: CostController_QueryJobCostsV2
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobCostsToDate/search:
    post:
      tags:
        - Cost
      summary: Returns a paginated list of job costs.
      description: "This call returns a paginated list of costs and hours spent per cost code for \r\nthe specified business unit, cost codes, jobs, or foremen.\r\nYou must request at least one of the following: businessUnitId, jobIds, jobTagIds, or costCodeIds."
      operationId: CostController_QueryJobCostsToDate
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobCostCustomCosts/advancedRequest:
    post:
      tags:
        - Cost
      summary: Returns a paginated list of job cost custom costs.
      operationId: CostController_QueryJobCostCustomCosts
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costCodes/{costCodeId}/costs:
    get:
      tags:
        - Cost
      summary: Returns cost code costs
      description: This list returns a list of cost code costs.
      operationId: CostController_GetCostCodeCosts
      security:
        - bearer:
            - heavyjob:read
    put:
      tags:
        - Cost
      summary: Sets costs for the cost code by creating adjustments.
      description: To adjust the trucking cost, use the associated custom cost type from the business unit preferences.
      operationId: CostController_UpdateCostCodeCosts
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/costAdjustments:
    get:
      tags:
        - CostAdjustment
      summary: Returns a list of cost adjustments.
      operationId: CostAdjustmentController_GetCostAdjustments
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - CostAdjustment
      summary: Creates cost adjustment
      description: This call creates a new cost adjustment.
      operationId: CostAdjustmentController_CreateCostAdjustment
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costAdjustments/{id}:
    put:
      tags:
        - CostAdjustment
      summary: Updates an existing cost adjustment by its id.
      operationId: CostAdjustmentController_UpdateCostAdjustment
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - CostAdjustment
      summary: Deletes a cost adjustment by its id.
      operationId: CostAdjustmentController_DeleteCostAdjustment
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costCodes:
    get:
      tags:
        - CostCode
      summary: Returns cost codes
      description: This call returns a list of cost codes with accounting values, if available, given business unit, job, cost code or accounting template.
      operationId: CostCodeController_GetCostCodesV1Async
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - CostCode
      summary: Creates a new cost code with accounting values.
      description: The code will be uppercased and trimmed of whitespace.
      operationId: CostCodeController_CreateCostCode
      security:
        - bearer:
            - heavyjob:write
    patch:
      tags:
        - CostCode
      summary: Creates or updates cost codes (up to 10000)
      description: "Creates or updates cost codes on the specified job.\r\n\r\nThis endpoint currently only supports the adding or updating of cost codes across \r\na single job. If more than one job ID is specified, the request will be rejected."
      operationId: CostCodeController_UpsertCostCodes
      security:
        - bearer:
            - heavyjob:write
  /api/v2/costCodes:
    get:
      tags:
        - CostCode
      summary: Returns cost codes
      description: This call returns a list of cost codes with accounting values, if available, given business unit, job, cost code, accounting template or modified since date.
      operationId: CostCodeController_GetCostCodesV2Async
      security:
        - bearer:
            - heavyjob:read
  /api/v2/costCodes/advancedRequest:
    post:
      tags:
        - CostCode
      summary: Returns cost codes
      description: This call returns a list of cost codes for the specified business unit, jobs, cost codes, or accounting template
      operationId: CostCodeController_GetCostCodesAdvancedRequestV2Async
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costCodes/search:
    post:
      tags:
        - CostCode
      summary: Returns cost codes
      description: "<span style='color: white; background-color: red; font-weight: bold; padding: 5px;'>VOLATILE</span>\n\t\t<span>The query parameters and responses are likely to change. Do not use this operation for mission-critical applications yet.</span>\n\t\t<br /><br />This call returns a list of cost codes for the specified business unit, jobs, job tags, and cost codes"
      operationId: CostCodeController_GetCostCodesSearchAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costCodes/customCostTypes:
    patch:
      tags:
        - CostCode
      summary: Creates or updates budgets for a list of cost code and custom cost type combination
      operationId: CostCodeController_CreateOrUpdateCustomCostTypeBudgetsAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costCode/progress/advancedRequest:
    post:
      tags:
        - CostCodeProgress
      summary: Returns a list of quantities for a given date range, job Id and other optional parameters.
      operationId: CostCodeProgressController_GetCostCodeProgressAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costCodeSetupFilters:
    get:
      tags:
        - CostCodeTag
      summary: Returns cost code setup tags with their groups
      description: This call returns a list of cost code setup tags with their groups.
      operationId: CostCodeTagController_GetCostCodeSetupFiltersAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costCodeTags:
    get:
      tags:
        - CostCodeTag
      summary: Returns a list of cost code - tag relationships.
      operationId: CostCodeTagController_GetCostCodeTags
      security:
        - bearer:
            - heavyjob:read
    delete:
      tags:
        - CostCodeTag
      summary: Deletes cost code - tag relationships.
      operationId: CostCodeTagController_DeleteCostCodeTags
      security:
        - bearer:
            - heavyjob:write
    patch:
      tags:
        - CostCodeTag
      summary: Upserts cost code setup tags
      description: This call creates and updates setup tags associated with cost codes.
      operationId: CostCodeTagController_UpsertCostCodeTags
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costCodeTags/advancedRequest:
    post:
      tags:
        - CostCodeTag
      summary: Returns cost codes with associated setup tags
      description: This call will return a list of cost codes and their associated setup tags for the specified cost codes, jobs, tags or modified since date.
      operationId: CostCodeTagController_QueryCostCodeTags
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costCodeTimeCardTransactions/advancedRequest:
    post:
      tags:
        - CostCodeTransaction
      summary: "Returns a paginated list of cost code time card transactions for the specified business unit or specified job list,\r\nor specified foreman list or specified date range."
      operationId: CostCodeTransactionController_GetCostCodeTimeCardTransactions
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costCodeTransactionAdjustments/advancedRequest:
    post:
      tags:
        - CostCodeTransactionAdjustment
      summary: Returns a list of cost code transaction adjustments.
      operationId: CostCodeTransactionAdjustmentController_GetCostCodeTransactionAdjustmentAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costTypeQuantities/materialInstalled:
    get:
      tags:
        - CostTypeQuantity
      summary: Returns installed material quantities
      description: This call returns a list of installed material quantities for the specified job, foreman, date range or modified since date.
      operationId: CostTypeQuantityController_GetMaterialInstalledQuantities
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costTypeQuantities/subcontractWorked:
    get:
      tags:
        - CostTypeQuantity
      summary: Returns subcontract work performed quantities
      description: This call returns a list of subcontract work performed quantities for the specified job, foreman, date range or modified since date.
      operationId: CostTypeQuantityController_GetSubcontractWorkQuantities
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costTypeQuantities/adjustments:
    get:
      tags:
        - CostTypeQuantity
      summary: Returns quantity adjustment changes
      description: This call returns a list of quantity changes that have been applied through quantity adjustments for the specified job, foreman, date range or modified since date.
      operationId: CostTypeQuantityController_GetQuantityAdjustments
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costTypeQuantities/customReceived/{id}:
    patch:
      tags:
        - CostTypeQuantity
      summary: Update an existing received custom cost type item with the values provided.
      operationId: CostTypeQuantityController_UpdateCustomCostTypeItemReceivedAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/costCategories:
    get:
      tags:
        - CustomCostType
      summary: Returns cost categories
      description: This call returns a list of cost categories for a business unit.
      operationId: CustomCostTypeController_GetCostCategories
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - CustomCostType
      summary: Creates cost category
      description: This call creates a cost category on a business unit.
      operationId: CustomCostTypeController_CreateCostCategory
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/costTypes/custom:
    get:
      tags:
        - CustomCostTypeItem
      summary: Returns custom cost type items
      description: Returns a list of custom cost type items for the specified business unit.
      operationId: CustomCostTypeItemController_GetCustomCostTypeItems
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - CustomCostTypeItem
      summary: Creates cost type item
      description: Creates a cost type item for the specified business unit.
      operationId: CustomCostTypeItemController_CreateCustomCostTypeItem
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/custom/{id}:
    put:
      tags:
        - CustomCostTypeItem
      summary: Updates custom cost type item
      description: Updates an existing custom cost type item with the specified id.
      operationId: CustomCostTypeItemController_UpdateCustomCostTypeItem
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - CustomCostTypeItem
      summary: Deletes a custom cost type item
      description: Deletes a custom cost type item with the specified id.
      operationId: CustomCostTypeItemController_DeleteCustomCostTypeItem
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobs/{jobId}/costTypes/jobCustom:
    get:
      tags:
        - CustomCostTypeItem
      summary: Returns job custom cost type items
      description: Returns a list of job custom cost type items.
      operationId: CustomCostTypeItemController_GetJobCustomCostTypeItems
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - CustomCostTypeItem
      summary: Creates job custom cost type item
      description: Creates a job custom cost type item on the specified job.
      operationId: CustomCostTypeItemController_CreateJobCustomCostTypeItem
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/jobCustom/{id}:
    get:
      tags:
        - CustomCostTypeItem
      summary: Returns a job custom cost type item
      description: Returns a job custom cost type item with the specified id.
      operationId: CustomCostTypeItemController_GetJobCustomCostTypeItem
      security:
        - bearer:
            - heavyjob:read
    put:
      tags:
        - CustomCostTypeItem
      summary: Updates job custom cost type item
      description: Updates an existing job custom cost type item with the specified id.
      operationId: CustomCostTypeItemController_UpdateJobCustomCostTypeItem
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - CustomCostTypeItem
      summary: Deletes job custom cost type item
      description: Deletes the job custom cost type item with the specified id.
      operationId: CustomCostTypeItemController_DeleteJobCustomCostTypeItem
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/customInstalled/advancedRequest:
    post:
      tags:
        - CustomCostTypeItem
      summary: Returns installed custom cost type items
      description: Returns a list of installed custom cost type items.
      operationId: CustomCostTypeItemController_GetCustomCostTypeInstalledPaginatedAdvanced
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costTypes/customReceived/advancedRequest:
    post:
      tags:
        - CustomCostTypeItem
      summary: Returns received custom cost type items
      description: Returns a list of received custom cost type items.
      operationId: CustomCostTypeItemController_GetCustomCostTypeReceivedPaginatedAdvanced
      security:
        - bearer:
            - heavyjob:read
  /api/v1/diaries/search:
    post:
      tags:
        - Diary
      summary: Returns a paginated list of diary summaries for a business unit, jobs, or foremen in a date range.
      operationId: DiaryController_QueryDiariesAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/diaries:
    put:
      tags:
        - Diary
      summary: Creates or updates a diary record
      operationId: DiaryController_UpsertDiary
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/employees:
    get:
      tags:
        - Employee
      summary: Returns employees for a business unit
      description: This call returns employees with accounting values for a specified business unit.
      operationId: EmployeeController_GetEmployeesAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/employees/advancedRequest:
    post:
      tags:
        - Employee
      summary: Returns employees
      description: This call returns a list of employees for the specified business unit, employees, accounting template, active status, foreman status, and deleted status.
      operationId: EmployeeController_GetEmployeesAdvancedAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/employees:
    get:
      tags:
        - Employee
      summary: Call to get Employee details that include physical address, cell phone and other phone.
      operationId: EmployeeController_GetEmployeesWithDetailsAsync
      security:
        - bearer:
            - heavyjob:read
    delete:
      tags:
        - Employee
      summary: "Delete an employee. Employee will be deleted at the company level, and business unit- or job-level \r\nrelationships will also be deleted."
      operationId: EmployeeController_DeleteEmployeeAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/equipment:
    get:
      tags:
        - Equipment
      summary: Returns a list of equipment for a business unit.
      operationId: EquipmentController_GetEquipmentAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/equipment/advancedRequest:
    post:
      tags:
        - Equipment
      summary: Returns a list of equipment.
      operationId: EquipmentController_GetEquipmentAdvancedAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/businessUnits/{businessUnitId}/equipment/{equipmentId}:
    put:
      tags:
        - Equipment
      summary: Updates an existing equipment
      operationId: EquipmentController_UpdateEquipmentAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/equipment/types:
    get:
      tags:
        - EquipmentType
      summary: Returns a list of equipment types.
      description: '<span style=''color: white; background-color: orange; font-weight: bold; padding: 5px;''>DEPRECATED</span> Please use the endpoint "/api/v1/equipmentTypes"<br /><br />'
      operationId: EquipmentTypeController_GetEquipmentTypesAsync
      deprecated: true
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - EquipmentType
      summary: Creates a new equipment type.
      description: '<span style=''color: white; background-color: orange; font-weight: bold; padding: 5px;''>DEPRECATED</span> Please use the endpoint "/api/v1/equipmentTypes"<br /><br />'
      operationId: EquipmentTypeController_CreateBusinessUnitEquipmentTypeAsync
      deprecated: true
      security:
        - bearer:
            - heavyjob:write
  /api/v1/equipmentTypes:
    get:
      tags:
        - EquipmentType
      summary: Returns a list of equipment types.
      operationId: EquipmentTypeController_GetEquipmentTypesV2Async
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - EquipmentType
      summary: Creates a new equipment type.
      operationId: EquipmentTypeController_CreateEquipmentTypeAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/forecastInfo:
    get:
      tags:
        - Forecast
      summary: Returns forecast summary information
      description: This call returns a paginated list of forecast summary information for the specified job, date range or finalized since date.
      operationId: ForecastController_GetForecastInfo
      security:
        - bearer:
            - heavyjob:read
  /api/v1/forecasts/{forecastId}:
    get:
      tags:
        - Forecast
      summary: Returns forecast details
      description: This call returns forecast details for the specified forecast id.
      operationId: ForecastController_GetForecast
      security:
        - bearer:
            - heavyjob:read
  /api/v1/hours/employees:
    post:
      tags:
        - Hours
      summary: Returns employee time card hours
      description: This call returns a paginated list of employee time card hours and cost adjustments for the specified business unit, jobs, foremen, employees, and date range.
      operationId: HoursController_GetEmployeeHoursAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/hours/equipment:
    post:
      tags:
        - Hours
      summary: Returns equipment time card hours
      description: This call returns a paginated list of equipment time card hours for the specified business unit, jobs, foremen, equipment, and date range.
      operationId: HoursController_GetEquipmentHoursAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/businessUnits/{businessUnitId}/attendanceHourTags:
    get:
      tags:
        - HourTag
      summary: Returns employee attendance hour tags
      description: This call returns a list of non-deleted employee attendance hour tags in a business unit.
      operationId: HourTagController_GetAttendanceHourTags
      security:
        - bearer:
            - heavyjob:read
  /api/v1/businessUnits/{businessUnitId}/nonuseHourTags:
    get:
      tags:
        - HourTag
      summary: Returns equipment non-use hour tags
      description: This call returns a list of equipment non-use hour tags in a business unit.
      operationId: HourTagController_GetNonuseHourTags
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobs:
    get:
      tags:
        - Job
      summary: Returns jobs by business unit
      description: This call will return a list of jobs for the specified business unit.
      operationId: JobController_GetJobsAsyncV1
      security:
        - bearer:
            - heavyjob:read
    patch:
      tags:
        - Job
      summary: Upserts multiple jobs
      description: "<span style='color: white; background-color: red; font-weight: bold; padding: 5px;'>VOLATILE</span>\n\t\t<span>The query parameters and responses are likely to change. Do not use this operation for mission-critical applications yet.</span>\n\t\t<br /><br />This call will add a list of jobs to update/insert to a queue to be ultimately processed."
      operationId: JobController_BulkProcessJobsAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobs/advanced:
    post:
      tags:
        - Job
      summary: Returns jobs by jobs or job tags
      description: This call will return a list of jobs for the specified jobs or job tags.
      operationId: JobController_GetJobsAdvancedAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobEmployees:
    get:
      tags:
        - JobEmployee
      summary: Returns job employees
      description: This call returns a list of job employees for the specified business unit, job or employee.
      operationId: JobEmployeeController_GetJobEmployees
      security:
        - bearer:
            - heavyjob:read
    delete:
      tags:
        - JobEmployee
      summary: Delete job-employee relationships.
      description: Either jobId or employeeId need to be provided
      operationId: JobEmployeeController_DeleteJobEmployees
      security:
        - bearer:
            - heavyjob:write
    patch:
      tags:
        - JobEmployee
      summary: Creates and updates job-employee relationships.
      description: "Note that passing a null value for defaultPayClassId or assignedEquipmentId will not null out and reset an\r\nalready filled in value, since this is a PATCH request."
      operationId: JobEmployeeController_UpsertJobEmployees
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobEquipment:
    patch:
      tags:
        - JobEquipment
      summary: Creates and updates job-equipment relationships.
      description: "Note that passing a null value for operatorPayClassCode will not null out and reset an\r\nalready filled in value, since this is a PATCH request."
      operationId: JobEquipmentController_UpsertJobEquipment
      security:
        - bearer:
            - heavyjob:write
    get:
      tags:
        - JobEquipment
      summary: Returns job equipment
      description: This call returns a list of job equipment for the specified business unit, job or equipment.
      operationId: JobEquipmentController_GetJobEquipment
      security:
        - bearer:
            - heavyjob:read
    delete:
      tags:
        - JobEquipment
      summary: Delete job-equipment relationships.
      operationId: JobEquipmentController_DeleteJobEquipment
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/costTypes/material:
    get:
      tags:
        - Material
      summary: Returns materials
      description: Returns a list of materials for the specified business unit.
      operationId: MaterialController_GetMaterials
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - Material
      summary: Creates material
      description: Creates a material for the specified business unit.
      operationId: MaterialController_CreateMaterial
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/material/{id}:
    put:
      tags:
        - Material
      summary: Updates material
      description: Updates an existing material with the specified id.
      operationId: MaterialController_UpdateMaterial
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - Material
      summary: Deletes a material
      description: Deletes a material with the specified id.
      operationId: MaterialController_DeleteMaterial
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobs/{jobId}/costTypes/jobMaterial:
    get:
      tags:
        - Material
      summary: Returns job materials
      description: Returns a list of job materials (i.e., a physical material that can be used on one or more cost codes).
      operationId: MaterialController_GetJobMaterials
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - Material
      summary: Creates job material
      description: Creates a job material on the specified job.
      operationId: MaterialController_CreateJobMaterial
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/jobMaterial/{id}:
    get:
      tags:
        - Material
      summary: Returns a job material
      description: Returns a job material with the specified id.
      operationId: MaterialController_GetJobMaterial
      security:
        - bearer:
            - heavyjob:read
    put:
      tags:
        - Material
      summary: Updates job material
      description: Updates an existing job material with the specified id.
      operationId: MaterialController_UpdateJobMaterial
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - Material
      summary: Deletes job material
      description: Deletes the job material with the specified id.
      operationId: MaterialController_DeleteJobMaterial
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/materialInstalled/advancedRequest:
    post:
      tags:
        - Material
      summary: Returns installed materials
      description: Returns a list of installed materials.
      operationId: MaterialController_GetMaterialsInstalledPaginatedAdvanced
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costTypes/materialReceived/advancedRequest:
    post:
      tags:
        - Material
      summary: Returns received materials
      description: Returns a list of received materials.
      operationId: MaterialController_GetMaterialsReceivedPaginatedAdvanced
      security:
        - bearer:
            - heavyjob:read
  /api/v1/costTypeItems:
    patch:
      tags:
        - MaterialSubsAndCustomCosts
      summary: Update or add new material, subcontract, or custom cost type items
      operationId: MaterialSubsAndCustomCostsController_UpsertLibraryMaterialsSubsAndCustomCostTypeItemsAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/payclass:
    get:
      tags:
        - PayClass
      summary: Returns pay classes in a business unit
      description: This call returns a list of pay classes in a business unit.
      operationId: PayClassController_GetPayClassListAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/payClasses/{id}:
    patch:
      tags:
        - PayClass
      summary: Updates a pay class in a business unit
      operationId: PayClassController_UpdatePayClassAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/payItems:
    get:
      tags:
        - PayItem
      summary: Returns pay items
      description: This call returns a list of pay items for the specified job.
      operationId: PayItemController_GetPayItems
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - PayItem
      summary: Creates a new pay item.
      description: "The combination of jobId and pay item code must be unique.\r\n            \r\nThe pay item code will be uppercased.  The pay item code,\r\ndescription, owner code, and unit of measure will be trimmed."
      operationId: PayItemController_CreatePayItemAsync
      security:
        - bearer:
            - heavyjob:write
    patch:
      tags:
        - PayItem
      summary: Bulk upsert pay items by code and job id.
      description: "The pay item code will be uppercased.  The pay item code,\r\ndescription, owner code, and unit of measure will be trimmed."
      operationId: PayItemController_BulkUpsertPayItemsAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v2/payItems:
    get:
      tags:
        - PayItem
      summary: Returns pay items
      description: "<span style='color: white; background-color: red; font-weight: bold; padding: 5px;'>VOLATILE</span>\n\t\t<span>The query parameters and responses are likely to change. Do not use this operation for mission-critical applications yet.</span>\n\t\t<br /><br />This call returns a list of pay items for the specified job."
      operationId: PayItemController_GetPayItemsV2Async
      security:
        - bearer:
            - heavyjob:read
  /api/v1/jobs/{jobId}/purchaseOrders:
    get:
      tags:
        - PurchaseOrder
      summary: Returns a list of purchase orders.
      description: '<span style=''color: white; background-color: orange; font-weight: bold; padding: 5px;''>DEPRECATED</span> Please use the endpoint "/api/v1/purchaseOrders"<br /><br />'
      operationId: PurchaseOrderController_GetJobPurchaseOrders
      deprecated: true
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - PurchaseOrder
      summary: Creates a new purchase order on the specified job.
      operationId: PurchaseOrderController_CreatePurchaseOrder
      security:
        - bearer:
            - heavyjob:write
  /api/v1/purchaseOrders:
    get:
      tags:
        - PurchaseOrder
      summary: Returns purchase orders
      description: This call returns a list of purchase orders for the specified business unit, job, purchase order, date range, or modified since date.
      operationId: PurchaseOrderController_GetPurchaseOrders
      security:
        - bearer:
            - heavyjob:read
  /api/v1/purchaseOrderItems:
    get:
      tags:
        - PurchaseOrder
      summary: Returns purchase order line items
      description: This call will return a list of purchase order line items for the specified business unit, job, purchase order or modified since date.
      operationId: PurchaseOrderController_GetPurchaseOrderItemsV1
      security:
        - bearer:
            - heavyjob:read
  /api/v1/purchaseOrders/{id}:
    put:
      tags:
        - PurchaseOrder
      summary: Updates a purchase order
      description: This call updates an existing purchase order by id. Canceling a purchase order is not supported yet.
      operationId: PurchaseOrderController_UpdatePurchaseOrder
      security:
        - bearer:
            - heavyjob:write
  /api/v1/purchaseOrders/{purchaseOrderId}/details/material:
    get:
      tags:
        - PurchaseOrder
      summary: "Returns a list of material purchase order details. \r\nThis endpoint only supports web-only companies."
      operationId: PurchaseOrderController_GetMaterialPurchaseOrderDetails
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - PurchaseOrder
      summary: Creates a material purchase order detail
      description: This call creates the specified job-level material purchase order detail.
      operationId: PurchaseOrderController_CreateMaterialPurchaseOrderDetail
      security:
        - bearer:
            - heavyjob:write
  /api/v1/purchaseOrders/details/material/{id}:
    put:
      tags:
        - PurchaseOrder
      summary: Updates material purchase order detail
      description: "This call updates an existing material purchase order detail by its id.\r\n            Currently, update is limited to isFullyReceived and isFullyInstalled fields only."
      operationId: PurchaseOrderController_UpdateMaterialPurchaseOrderDetail
      security:
        - bearer:
            - heavyjob:write
  /api/v1/quantityAdjustment:
    post:
      tags:
        - QuantityAdjustment
      summary: "Creates a new quantity adjustment for a job.\r\nThis endpoint only supports web-only companies."
      operationId: QuantityAdjustmentController_CreateQuantityAdjustmentAsync
      security:
        - bearer:
            - heavyjob:write
  /api/v1/releaseOrders/approvalRules/approvers:
    delete:
      tags:
        - ReleaseOrderApprovalRule
      summary: Deletes release order approval rule approvers
      operationId: ReleaseOrderApprovalRuleController_DeleteReleaseOrderApprovalRuleApprovers
      security:
        - bearer:
            - heavyjob:write
  /api/v1/businessUnits/{businessUnitId}/costTypes/subcontract:
    get:
      tags:
        - Subcontract
      summary: Returns subcontract items
      description: Returns a list of subcontract items for the specified business unit.
      operationId: SubcontractController_GetSubcontracts
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - Subcontract
      summary: Creates subcontract item
      description: Creates a subcontract item for the specified business unit.
      operationId: SubcontractController_CreateSubcontract
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/subcontract/{id}:
    put:
      tags:
        - Subcontract
      summary: Updates subcontract item
      description: Updates an existing subcontract item given its id.
      operationId: SubcontractController_UpdateSubcontract
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - Subcontract
      summary: Deletes a subcontract item
      description: Deletes a subcontract item given its id.
      operationId: SubcontractController_DeleteSubcontract
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobs/{jobId}/costTypes/jobSubcontract:
    get:
      tags:
        - Subcontract
      summary: Returns job subcontract items
      description: Returns a list of job subcontract items (i.e., subcontractor work that can be done on one or more cost codes).
      operationId: SubcontractController_GetJobSubcontracts
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - Subcontract
      summary: Creates job subcontract item
      description: Creates a job subcontract item on the specified job.
      operationId: SubcontractController_CreateJobSubcontract
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/jobSubcontract/{id}:
    get:
      tags:
        - Subcontract
      summary: Returns a job subcontract item
      description: Returns a job subcontract item with the specified id.
      operationId: SubcontractController_GetJobSubcontract
      security:
        - bearer:
            - heavyjob:read
    put:
      tags:
        - Subcontract
      summary: Updates job subcontract item
      description: Updates an existing job subcontract item with the specified id.
      operationId: SubcontractController_UpdateJobSubcontract
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - Subcontract
      summary: Deletes job subcontract item
      description: Deletes the job subcontract item with the specified id.
      operationId: SubcontractController_DeleteJobSubcontract
      security:
        - bearer:
            - heavyjob:write
  /api/v1/costTypes/subcontractWork/advancedRequest:
    post:
      tags:
        - Subcontract
      summary: Returns subcontract transactions
      description: Returns a list of subcontract transactions.
      operationId: SubcontractController_GetSubcontractWorkPaginatedAdvanced
      security:
        - bearer:
            - heavyjob:read
  /api/v1/timeCardApprovalInfo:
    get:
      tags:
        - TimeCard
      summary: Returns time card approvals
      description: "This call returns a paginated list of time card summary information with approvals for the specified job, foreman, and date range.\r\nIf there are additional pages, the response metadata will include a \"nextCursor\" field.  That field should be passed as the \"cursor\" query parameter to request the next page of results."
      operationId: TimeCardController_GetTimeCardApprovalInfo
      security:
        - bearer:
            - timecards:read
  /api/v1/timeCardInfo:
    get:
      tags:
        - TimeCard
      summary: Returns time cards
      description: "This call Returns a paginated list of time card summary information for the specified job, foreman, and date range.\r\nIf there are additional pages, the response metadata will include a \"nextCursor\" field.  That field should be passed as the \"cursor\" query parameter to request the next page of results."
      operationId: TimeCardController_GetTimeCardInfo
      security:
        - bearer:
            - timecards:read
  /api/v1/timeCards/{id}:
    get:
      tags:
        - TimeCard
      summary: Returns the time card with the specified id.
      operationId: TimeCardController_GetTimeCard
      security:
        - bearer:
            - timecards:read
    put:
      tags:
        - TimeCard
      summary: Updates time card
      description: Updates an existing time card by id. Sent-to-payroll revision and sent-to-payroll datetime are the only fields supported at this time.
      operationId: TimeCardController_UpdateTimeCard
      security:
        - bearer:
            - timecards:write
  /api/v1/businessUnits/{businessUnitId}/missingTimeCards:
    get:
      tags:
        - TimeCard
      summary: Returns list of foremen with missing time cards for a specified business unit and date who have previously submitted in a specified date range.
      operationId: TimeCardController_GetMissingTimeCardForemen
      security:
        - bearer:
            - timecards:read
  /api/v1/timeCardEquipment:
    get:
      tags:
        - TimeCard
      summary: Returns time card data using a piece of equipment
      description: This call returns time card data for time cards that used a given piece of equipment on a given date.
      operationId: TimeCardController_FindTimeCardsForEquipmentAsync
      security:
        - bearer:
            - heavyjob:read
  /api/v1/users/{id}:
    get:
      tags:
        - User
      summary: Returns a user
      description: "This call returns the user's first name, last name, email address, and the\r\nassociated employee for the specified id."
      operationId: UserController_GetUser
      security:
        - bearer:
            - heavyjob:read
  /api/v1/userAccessGroup/search:
    post:
      tags:
        - UserAccessGroup
      summary: Returns list of users' access groups
      description: This call returns the users' access groups.
      operationId: UserAccessGroupController_GetAllAsync
      security:
        - bearer:
            - heavyjob:users:read
  /api/v1/userAccessGroup:
    patch:
      tags:
        - UserAccessGroup
      summary: Updates access group for users
      description: This call  updates the users' access group.
      operationId: UserAccessGroupController_UpdateAsync
      security:
        - bearer:
            - heavyjob:users:write
  /api/v1/vendors:
    get:
      tags:
        - Vendor
      summary: Returns vendors
      description: This call returns a list of vendors.
      operationId: VendorController_GetAllVendors
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - Vendor
      summary: Creates a new vendor.  Names and descriptions may be duplicated.
      operationId: VendorController_CreateVendor
      security:
        - bearer:
            - heavyjob:write
  /api/v2/vendors:
    get:
      tags:
        - Vendor
      summary: Returns a list of vendors, respecting the isDeleted and modifiedSince parameters.
      operationId: VendorController_GetAllVendorsV2
      security:
        - bearer:
            - heavyjob:read
  /api/v1/vendors/{id}:
    put:
      tags:
        - Vendor
      summary: Updates a vendor
      description: This call updates an existing vendor by its id.
      operationId: VendorController_UpdateVendor
      security:
        - bearer:
            - heavyjob:write
    delete:
      tags:
        - Vendor
      summary: Deletes a vendor by its id.
      operationId: VendorController_DeleteVendor
      security:
        - bearer:
            - heavyjob:write
  /api/v1/jobs/{jobId}/vendorContracts:
    get:
      tags:
        - VendorContract
      summary: Returns vendor contracts
      description: '<span style=''color: white; background-color: orange; font-weight: bold; padding: 5px;''>DEPRECATED</span> Please use the endpoint "/api/v1/vendorContracts"<br /><br />This call returns a list of vendor contracts for the specified job.'
      operationId: VendorContractController_GetVendorContracts
      deprecated: true
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - VendorContract
      summary: Creates a new vendor contract.
      operationId: VendorContractController_CreateVendorContract
      security:
        - bearer:
            - heavyjob:write
  /api/v1/vendorContracts:
    get:
      tags:
        - VendorContract
      summary: Returns vendor contracts
      description: This call returns a list of vendor contracts for a specified job, business unit, vendor contract or modified since date.
      operationId: VendorContractController_GetVendorContractsPaginated
      security:
        - bearer:
            - heavyjob:read
  /api/v1/vendorContracts/{id}:
    put:
      tags:
        - VendorContract
      summary: Updates a vendor contract
      description: "This call updates an existing vendor contract by its id.  Cancelling a vendor\r\ncontract is not supported yet."
      operationId: VendorContractController_UpdateVendorContract
      security:
        - bearer:
            - heavyjob:write
  /api/v1/vendorContracts/{vendorContractId}/details:
    get:
      tags:
        - VendorContract
      summary: Returns a list of vendor contract details.
      operationId: VendorContractController_GetVendorContractDetails
      security:
        - bearer:
            - heavyjob:read
    post:
      tags:
        - VendorContract
      summary: Creates a vendor contract detail
      description: This call creates a new vendor contract detail.
      operationId: VendorContractController_CreateVendorContractDetails
      security:
        - bearer:
            - heavyjob:write
  /api/v1/vendorContractItems:
    get:
      tags:
        - VendorContract
      summary: Returns vendor contract items
      description: This call returns a list of vendor contract items for the specified job, business unit, vendor contract, and modified since date.
      operationId: VendorContractController_GetVendorContractItemsPaginated
      security:
        - bearer:
            - heavyjob:read
  /api/v1/vendorContracts/details/{id}:
    put:
      tags:
        - VendorContract
      summary: Updates a vendor contract detail
      description: "This call updates an existing vendor contract detail by its id.\r\nCurrently, update is limited to IsCompleted field only."
      operationId: VendorContractController_UpdateVendorContractDetail
      security:
        - bearer:
            - heavyjob:write
components:
  securitySchemes:
    bearer:
      type: oauth2
      description: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.hcssapps.com/identity/connect/token
          scopes:
            heavyjob:read: heavyjob:read
            heavyjob:write: heavyjob:write
            timecards:read: timecards:read
            timecards:write: timecards:write
            heavyjob:users:read: heavyjob:users:read
            heavyjob:users:write: heavyjob:users:write
        authorizationCode:
          tokenUrl: https://api.hcssapps.com/identity/connect/token
          authorizationUrl: https://api.hcssapps.com/identity/connect/authorize
          scopes:
            heavyjob:read: heavyjob:read
            heavyjob:write: heavyjob:write
            timecards:read: timecards:read
            timecards:write: timecards:write
            heavyjob:users:read: heavyjob:users:read
            heavyjob:users:write: heavyjob:users:write
